<?php
// Generated by ZF2's ./bin/classmap_generator.php
// As we are in development, we don’t need to load files via the classmap, so we provide an empty array for the classmap autoloader. Create a file called autoload_classmap.php under zf2-tutorial/module/Album:
// return array(
//     'Album\Module'                        => __DIR__ . '/Module.php',
//     'Album\Controller\AlbumController' => __DIR__ . '/src/Album/Controller/AlbumController.php',
//     'AlbumTest\Framework\TestCase'        => __DIR__ . '/tests/Album/Framework/TestCase.php',
//     'AlbumTest\SampleTest'                => __DIR__ . '/tests/Album/SampleTest.php',
// );
return array();
